spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: prajna
    password:
    driverClassName: org.h2.Driver
    tomcat:
      validation-query-timeout: 1
      test-while-idle: true
      test-on-borrow: true
      test-on-return: true
      initial-size: 2
      min-idle: 1
      max-idle: 4
      max-active: 8
      max-wait: 3000
      min-evictable-idle-time-millis: 60000
      log-abandoned: true
      log-validation-errors: true
  h2:
    console.enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
xss:
  enabled: true
