spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/customer
    username: postgres
    password: postgres
    platform: POSTGRESQL
    hikari:
      data-source-properties:
        stringtype: unspecified
    tomcat:
      validation-query-timeout: 1
      test-while-idle: true
      test-on-borrow: true
      test-on-return: true
      initial-size: 2
      min-idle: 1
      max-idle: 4
      max-active: 8
      max-wait: 3000
      min-evictable-idle-time-millis: 60000
      log-abandoned: true
      log-validation-errors: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
      use-new-id-generator-mappings: false
      jdbc:
        batch_size: 1000
    show-sql: true
    properties:
      hibernate:
        format_sql:    true
        jdbc:
          batch_size:  1000
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
        hbm2ddl:
          auto: none
        default_schema: public

xss:
  enabled: true
